stages:
  - build

before_script:
  - 'dotnet restore'

build:
 stage: build
 script:
  - 'dotnet pack ./src/JsonApiDotNetCore -c Release -o ./artifacts'
  - 'mono NuGet.exe push ./artifacts/*.nupkg %NugetAPIKey% -Source %NugetSource%'
 only:
   - master