stages:
  - build
  - deploy

before_script:
  - 'sudo dotnet restore'

build:
 stage: build
 script:
  - dotnet pack ./src/JsonApiDotNetCore -c Release -o ./artifacts
  - mono /bin/NuGet.exe push artifacts/*.nupkg $NUGET_KEY -Source $NUGET_SOURCE
 only:
   - master
