stages:
  - build
  - deploy

before_script:
  - 'sudo dotnet restore'

build:
 stage: build
 script:
  - 'dotnet pack ./src/JsonApiDotNetCore -c Release -o ./artifacts'
 only:
   - master

publish:
  stage: deploy
  script:
   - 'mono /bin/NuGet.exe push ./artifacts/*.nupkg $NUGET_KEY -Source $NUGET_SOURCE'
  only:
   - tags