language: csharp
dist: trusty
sudo: required
services: 
 - postgresql
before_script:
  - psql -c 'create database JsonApiDotNetCoreExample;' -U postgres
mono: none
dotnet: 1.0.4 # https://www.microsoft.com/net/download/linux
branches:
  only:
    - master
    - develop
script:
  - ./build.sh
