language: csharp
dist: trusty
sudo: required
services: 
 - postgresql
before_script:
  - psql -c 'create database JsonApiDotNetCoreExample;' -U postgres
mono: none
dotnet: 1.0.1
branches:
  only:
    - master
    - develop
script:
  - ./build.sh
