language: csharp
sudo: required
services:
 - postgresql
before_script:
  - psql -c 'create database JsonApiDotNetCoreExample;' -U postgres
mono: none
dotnet: 3.0.100 # https://www.microsoft.com/net/download/linux
branches:
  only:
    - master
    - develop
script:
  - ./build.sh
