version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - staging
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\Build.ps1
test: off
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://www.myget.org/F/research-institute/api/v2/package
  api_key:
    secure: 6CeYcZ4Ze+57gxfeuHzqP6ldbUkPtF6pfpVM1Gw/K2jExFrAz763gNAQ++tiacq3
  skip_symbols: true
  on:
    branch: staging
- provider: NuGet
  name: production
  api_key:
    secure: /fsEOgG4EdtNd6DPmko9h3NxQwx1IGDcFreGTKd2KA56U2KEkpX/L/pCGpCIEf2s
  on:
    branch: master
    appveyor_repo_tag: true